apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-modect
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 1
      containers:
        - image: raghavtiruvallur/knative-modect:latest
          ports:
            - containerPort: 8080

