apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatemodel
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      faas_function: updatemodel
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        faas_function: updatemodel
    spec:
      runtimeClassName: nvidia
      containers:
      - env:
        - name: read_timeout
          value: 1500s
        - name: write_timeout
          value: 1500s
        - name: exec_timeout
          value: 1500s
        - name: MINIO_ADDRESS
          value: 172.17.0.3:9000
        image: flowbench2024/update_model
        resources:
          limits:
            nvidia.com/gpu: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        name: updatemodel
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /mnt/local-storage
          name: local-storage
      volumes:
      - name: local-storage
        persistentVolumeClaim:
          claimName: local-storage-claim
