apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: va-monolith
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/target: '20'
    spec:
      containers:
      - env:
        - name: OUTPUTBUCKET1
          value: stage1
        - name: OUTPUTBUCKET2
          value: stage2
        - name: OUTPUTBUCKET3
          value: stage3
        - name: OUTPUTBUCKET4
          value: stage4
        - name: ENDPOINTINPUT
          value: 192.168.1.111:9000
        - name: MODECT_MIN_AREA
          value: '5'
        - name: MODECT_SKIP_RATE
          value: '5'
        - name: ACCELERATION
          value: cpu
        image: flowbench2024/va-monolith
