
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gpu-test
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/flowbench2024/knative-facerec-latest
          resources:
            requests:
              nvidia.com/gpu: "1"  # Request 1 GPU
            limits:
              nvidia.com/gpu: "1"  # Limit to 1 GPU
          env:
          - name: ACCELERATION
            value: "gpu"
          - name: OUTPUTBUCKET
            value: "stage4"
          - name: STORAGE_TYPE
            value: "obj"
          - name: ENDPOINTINPUT
            value: "172.17.0.3:9000"
          - name: MN_FS
            value: "false"
