provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:

  vidsplit:
    lang: python3
    handler: ../demos/video-analytics-revised/vidsplit
    image: raghavtiruvallur/vidsplit:latest
    environment:
      OUTPUTBUCKET: stage1
      ENDPOINTINPUT: 172.17.0.2:9000
      PUSHGATEWAY_IP: 172.17.0.3:9091
      write_debug: true
      STORAGE_TYPE: obj
      MN_FS: false
   

  modect:
    lang: dockerfile
    handler: ../demos/video-analytics-revised/modect
    image: raghavtiruvallur/modect:latest
    environment:
      OUTPUTBUCKET: stage2
      ENDPOINTINPUT: 172.17.0.2:9000
      PUSHGATEWAY_IP: 172.17.0.3:9091
      STORAGE_TYPE: obj
      PIPELINE_STAGE: 2
      MODECT_MIN_AREA: 5
      MODECT_SKIP_RATE: 1
      write_debug: true
      MN_FS: false

  facextract:
    lang: dockerfile
    handler: ../demos/video-analytics-revised/facextract
    image: raghavtiruvallur/facextract:latest
    environment:
      OUTPUTBUCKET: stage3
      ENDPOINTINPUT: 172.17.0.2:9000
      PUSHGATEWAY_IP: 172.17.0.3:9091
      STORAGE_TYPE: obj
      write_debug: true
      MN_FS: false

  facerec:
    lang: dockerfile
    handler: ../demos/video-analytics-revised/facerec
    image: raghavtiruvallur/facerec:latest
    environment:
      OUTPUTBUCKET: stage4
      ENDPOINTINPUT: 172.17.0.2:9000
      PUSHGATEWAY_IP: 172.17.0.3:9091
      STORAGE_TYPE: obj
      write_debug: true
      MN_FS: false
 