version: '1.0'
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  vidsplit:
    lang: python3
    handler: ../demos/video-analytics-revised/vidsplit
    image: raghavtiruvallur/vidsplit:latest
    environment:
      OUTPUTBUCKET: stage1
      OUTPUTMODE: obj
      INPUTMODE: obj
      write_debug: true
