apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vidsplit
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
    spec:
      containers:
      - env:
        - name: NEXT_URL
          value: http://modect.default.svc.cluster.local
        - name: OUTPUTBUCKET
          value: stage1
        - name: write_debug
          value: 'True'
        - name: STORAGE_TYPE
          value: obj
        - name: MN_FS
          value: 'False'
        - name: ENDPOINTINPUT
          value: 172.17.0.3:9000
        - name: PUSHGATEWAY_IP
          value: prom-pushgateway.default.svc.cluster.local:9091
        image: flowbench2024/knative-vidsplit-stateful
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: modect
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
    spec:
      containers:
      - env:
        - name: NEXT_URL
          value: http://facextract.default.svc.cluster.local
        - name: OUTPUTBUCKET
          value: stage2
        - name: STORAGE_TYPE
          value: obj
        - name: PIPELINE_STAGE
          value: '2'
        - name: MODECT_MIN_AREA
          value: '5'
        - name: MODECT_SKIP_RATE
          value: '1'
        - name: write_debug
          value: 'True'
        - name: MN_FS
          value: 'False'
        - name: ENDPOINTINPUT
          value: 172.17.0.3:9000
        - name: PUSHGATEWAY_IP
          value: prom-pushgateway.default.svc.cluster.local:9091
        image: flowbench2024/knative-modect-stateful
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: facextract
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
    spec:
      containers:
      - env:
        - name: NEXT_URL
          value: http://facerec.default.svc.cluster.local
        - name: OUTPUTBUCKET
          value: stage3
        - name: STORAGE_TYPE
          value: obj
        - name: PIPELINE_STAGE
          value: '2'
        - name: MODECT_MIN_AREA
          value: '5'
        - name: MODECT_SKIP_RATE
          value: '1'
        - name: write_debug
          value: 'True'
        - name: MN_FS
          value: 'False'
        - name: ENDPOINTINPUT
          value: 172.17.0.3:9000
        - name: PUSHGATEWAY_IP
          value: prom-pushgateway.default.svc.cluster.local:9091
        image: flowbench2024/knative-facextract-stateful
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: facerec
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
    spec:
      containers:
      - env:
        - name: OUTPUTBUCKET
          value: stage4
        - name: STORAGE_TYPE
          value: obj
        - name: PIPELINE_STAGE
          value: '2'
        - name: MODECT_MIN_AREA
          value: '5'
        - name: MODECT_SKIP_RATE
          value: '1'
        - name: write_debug
          value: 'True'
        - name: MN_FS
          value: 'False'
        - name: ENDPOINTINPUT
          value: 172.17.0.3:9000
        - name: PUSHGATEWAY_IP
          value: prom-pushgateway.default.svc.cluster.local:9091
        image: flowbench2024/knative-facerec-stateful
