document:
  dsl: 1.0.0-alpha1
  namespace: vanamespace
  name: videoanalytics
  version: 0.1.0
do:
  - vidsplit:
      do:
        - handle:
            entry: ../demos/knative/vidsplit
            execute: true
      image: flowbench2024/knative-vidsplit-stateful
      environment:
        NEXT_URL: "http://modect.default.svc.cluster.local"
        OUTPUTBUCKET: stage1
        write_debug: true
        STORAGE_TYPE: obj
        MN_FS: false
        ENDPOINTINPUT: "172.17.0.3:9000"
        PUSHGATEWAY_IP: "prom-pushgateway.default.svc.cluster.local:9091"
  - modect:
      do:
        - handle:
            entry: ../demos/knative/modect
            execute: true
      image: flowbench2024/knative-modect-stateful
      environment:
        NEXT_URL: "http://facextract.default.svc.cluster.local"
        OUTPUTBUCKET: stage2
        STORAGE_TYPE: obj
        PIPELINE_STAGE: 2
        MODECT_MIN_AREA: 5
        MODECT_SKIP_RATE: 1
        write_debug: true
        MN_FS: false
        ENDPOINTINPUT: "172.17.0.3:9000"
        PUSHGATEWAY_IP: "prom-pushgateway.default.svc.cluster.local:9091"
  - facextract:
      do:
        - handle:
            entry: ../demos/knative/facextract
            execute: true
      image: flowbench2024/knative-facextract-stateful
      environment:
        NEXT_URL: "http://facerec.default.svc.cluster.local"
        OUTPUTBUCKET: stage3
        STORAGE_TYPE: obj
        PIPELINE_STAGE: 2
        MODECT_MIN_AREA: 5
        MODECT_SKIP_RATE: 1
        write_debug: true
        MN_FS: false
        ENDPOINTINPUT: "172.17.0.3:9000"
        PUSHGATEWAY_IP: "prom-pushgateway.default.svc.cluster.local:9091"
  - facerec:
      do:
        - handle:
            entry: ../demos/knative/facerec
            execute: true
      image: flowbench2024/knative-facerec-stateful
      environment:
        OUTPUTBUCKET: stage4
        STORAGE_TYPE: obj
        PIPELINE_STAGE: 2
        MODECT_MIN_AREA: 5
        MODECT_SKIP_RATE: 1
        write_debug: true
        MN_FS: false
        ENDPOINTINPUT: "172.17.0.3:9000"
        PUSHGATEWAY_IP: "prom-pushgateway.default.svc.cluster.local:9091"
      
