apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: openfaas-fn
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: <local storage path>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath-immediate
