apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-claim
  namespace: openfaas-fn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath-immediate
