apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: openfaas-fn
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi