apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: openfaas-fn
spec:
  # nodeSelector:
    # node.kubernetes.io/microk8s-controlplane: microk8s-controlplane
    # slave: "2"

  containers:
  - name: test-container
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: /mnt/nfs-storage
      name: nfs-storage
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: my-pvc