apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-stateful-monolithic
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      faas_function: va-stateful-monolithic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        faas_function: va-stateful-monolithic
    spec:
      containers:
      - env:
        - name: INPUTMODE
          value: local
        - name: OUTPUTMODE
          value: local
        - name: OUTPUTBUCKET1
          value: stage1
        - name: OUTPUTBUCKET2
          value: stage2
        - name: OUTPUTBUCKET3
          value: stage3
        - name: OUTPUTBUCKET4
          value: stage4
        - name: MOUNT_PATH
          value: /mnt/local-storage
        - name: STORAGE_TYPE
          value: local
        - name: PVC_NAME
          value: local-storage-claim
        - name: MN_FS
          value: 'False'
        - name: write_debug
          value: 'True'
        image: raghavtiruvallur/va-stateful-monolithic:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        name: va-stateful-monolithic
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /mnt/local-storage
          name: local-storage
      volumes:
      - name: local-storage
        persistentVolumeClaim:
          claimName: local-storage-claim
