apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: openfaas-fn
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/users/harshit/project/local-storage
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath-immediate
