apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-facerec-final
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/flowbench2024/knative-facerec-new
        resources:
          requests:
            nvidia.com/gpu: "1"  # Request 1 GPU
          limits:
            nvidia.com/gpu: "1"
        env:
        - name: OUTPUTBUCKET
          value: "stage4"
        - name: STORAGE_TYPE
          value: "obj"
        - name: ENDPOINTINPUT
          value: "172.17.0.3:9000"
        - name: PUSHGATEWAY_IP
          value: "172.17.0.2:9091"
        - name: MN_FS
          value: "false"
        - name: "ACCELERATION"
          value: "gpu"
