provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:

  function:
    lang: dockerfile
    handler: ./va-monolith
    image: flowbench2024/function:latest
    environment:
      ENDPOINTINPUT: 172.17.0.3:9000
      OUTPUTBUCKET1: stage1
      OUTPUTBUCKET2: stage2
      OUTPUTBUCKET3: stage3
      OUTPUTBUCKET4: stage4
      PIPELINE_STAGE: 2
      MODECT_MIN_AREA: 5
      MODECT_SKIP_RATE: 1
      STORAGE_TYPE: obj
      PACKAGES_SOURCE: /home/app/function/vidsplit/tmp
      MOUNT_PATH: /home/users/harshit/project/local-storage
      INPUTMODE: obj
      OUTPUTMODE: obj
      write_debug: true
      PVC_NAME: 'local-storage-claim'