apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-pushgateway.fullname" . }}
  labels:
    app: {{ include "prom-pushgateway.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9091
      protocol: TCP
      name: http  
  selector:
    app: {{ include "prom-pushgateway.name" . }}
