replicaCount: 1

image:
  repository: prom/pushgateway
  tag: v1.4.0
  pullPolicy: IfNotPresent

release: "prometheus"
service:
  type: ClusterIP
  port: 9091

serviceMonitor:
  enabled: true
  interval: 30s
